name: nUTK CI Plan
run-name: ${{ github.actor }} | nUtk Build and Testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - run: echo "==> The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "==> This job is now running on a ${{ runner.os }}"
      - run: echo "==> The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "This job's status is ${{ job.status }}."
